#pragma once

enum MessageType {
    REQUEST_SCENE = 1,
    SEND_SCENE = 2,
    CHAT_MESSAGE = 3,
    REQUEST_PLAYER_SPAWN = 4,
    SEND_PLAYER_SPAWN = 5,
    SEND_PLAYER_STATE = 6,
    BROATCAST_PLAYER_STATE = 7,
    SEND_PLAYER_ID = 8,
    FIRE_MESSAGE = 9
};